Repository Les-Jailes/Admin_panel, pull requests merged in 2023-11, with the labels that each got.

#2 Admin Pabel Panel Backend Integration
  package-lock.json
  package.json
  src/app/AddProductForm.js
  src/app/api.js
Labels: feature

#3 Feature/ID-08/AdminPanelStyles
  src/app/AddProductForm.css
  src/app/AddProductForm.js
  src/app/CheckboxWithQuantity.js
  src/app/DeleteButton.jsx
  src/app/ImageButton.js
  src/app/InputField.js
  src/app/SelectField.js
  src/app/TextAreaField.js
  src/app/api.js
  src/app/colorInput.css
  src/app/page.module.css
  src/components/navbar/navbar.module.css
Labels: feature

#4 [BUG] ID-01/Code Section Permissions
  src/app/AddProductForm.css
  src/app/AddProductForm.js
  src/app/colorInput.css
  src/app/logout/loading.jsx
  src/app/logout/page.jsx
  src/app/page.js
  src/app/page.module.css
  src/components/AddProducts/AddProductForm.jsx
  src/components/AddProducts/FormDataOperations/FormHandlers.jsx
  src/components/AddProducts/FormDataOperations/useEffect.jsx
  src/components/AddProducts/ProductComponents/CheckboxWithQuantity.jsx
  src/components/AddProducts/ProductComponents/DeleteButton.jsx
  src/components/AddProducts/ProductComponents/ImageButton.jsx
  src/components/AddProducts/ProductComponents/InputField.jsx
  src/components/AddProducts/ProductComponents/SelectField.jsx
  src/components/AddProducts/ProductComponents/TextAreaField.jsx
  src/components/Api/api.js
  src/css/AddProducts/AddProductForm.css
  src/css/AddProducts/FormContainer.css
  src/css/AddProducts/ImagePathContainer.css
  src/css/AddProducts/InputContainer.css
  src/css/AddProducts/PageContainer.css
  src/utils/Form/sizeClothes.jsx
  src/utils/Form/typesClothes.jsx
Labels: bug

#5 404 page implementation
  public/bg-404.jpg
  src/app/globals.css
  src/app/not-found.jsx
Labels: task

#7 delete implementation with sweet alert and axios & api
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.js
  src/components/AddProducts/GetProductForm.jsx
  src/css/AddProducts/GetProductForm.css
  src/css/updateProducts/updateForm.css
Labels: task

#10 Feature/us 5 admin panel
  package-lock.json
  package.json
  public/bg-404.jpg
  src/app/add/loading.jsx
  src/app/add/page.jsx
  src/app/edit/[id]/page.jsx
  src/app/globals.css
  src/app/not-found.jsx
  src/app/page.js
  src/components/AddProducts/AddProductForm.jsx
  src/components/AddProducts/EditProductForm.jsx
  src/components/AddProducts/FormDataOperations/FormHandlers.jsx
  src/components/AddProducts/GetProductForm.jsx
  src/css/AddProducts/FormContainer.css
  src/css/AddProducts/GetProductForm.css
  src/css/updateProducts/updateForm.css
Labels: feature

#11 Feature/US-41/List-available-countries-frontend-admin-panel
  package-lock.json
  package.json
  src/app/countries/country-form/page.jsx
  src/app/countries/page.jsx
  src/components/Countries/AvailableCountries.jsx
  src/components/Countries/CountryForm.jsx
  src/css/Countries/AvailableCountries.css
  src/css/Countries/CountryForm.css
Labels: feature

#12 Deploy
  package-lock.json
  package.json
  public/bg-404.jpg
  src/app/add/loading.jsx
  src/app/add/page.jsx
  src/app/countries/country-form/page.jsx
  src/app/countries/page.jsx
  src/app/edit/[id]/page.jsx
  src/app/globals.css
  src/app/not-found.jsx
  src/app/page.js
  src/components/AddProducts/AddProductForm.jsx
  src/components/AddProducts/EditProductForm.jsx
  src/components/AddProducts/FormDataOperations/FormHandlers.jsx
  src/components/AddProducts/GetProductForm.jsx
  src/components/Countries/AvailableCountries.jsx
  src/components/Countries/CountryForm.jsx
  src/css/AddProducts/FormContainer.css
  src/css/AddProducts/GetProductForm.css
  src/css/Countries/AvailableCountries.css
  src/css/Countries/CountryForm.css
  src/css/updateProducts/updateForm.css
Labels: deploy

#13 Bug/ID-28-30-31/List-Available-Contries-fronted-admin panel
  src/components/Countries/CountryForm.jsx
Labels: bug

#14 Deply
  src/components/Countries/CountryForm.jsx
Labels: deploy

#17 Deploy
  src/components/AddProducts/AddProductForm.jsx
  src/components/AddProducts/EditProductForm.jsx
  src/components/AddProducts/FormDataOperations/FormHandlers.jsx
  src/components/Countries/CountryForm.jsx
Labels: deploy

#18 Deploy
  src/utils/menuItems.js
Labels: deploy
